apiVersion: v1
data:
  access_key_id: eHh4
  auth_method: YWNjZXNzX2tleQ==
  bucket: YmF6ZWwtcmVtb3Rl
  endpoint: aHR0cHM6Ly9zMy5hcC1ub3J0aGVhc3QtMS5hbWF6b25hd3MuY29t
  secret_access_key: eHh4
kind: Secret
metadata:
  creationTimestamp: null
  name: bazel-remote-s3
