name: Release manually

on:
  workflow_dispatch:
    inputs:
      last_release_commit:
        description: 'The commit hash/tag of the last release.'
        required: false

permissions:
  contents: read
  packages: write

# Concurrency should not be enabled for manual triggers.
# It will be deadlock if the same value is set as concurrency group for both of caller/called workflow.
# concurrency:
#   group: release

jobs:
  release:
    uses: ./.github/workflows/release.yaml
    with:
      last_release_commit: ${{ github.event.inputs.last_release_commit }}
